name: Android CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
    - name: Install Dependecies
      run: |
        sudo apt install tree p7zip
        gradle wrapper
    - name: Prepare Dobby Library
      run: |
        # Example of downloading Dobby (adjust URL and method as needed)
        git clone https://github.com/chiteroman/Dobby.git
        mv Dobby app/src/main/jni

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: |
        ./gradlew build -x lint
    - name: List Files & Folders
      run: tree
    - name: Rename each library so
      run: |
        7z a -tzip library.zip app/build/intermediates/cxx/Release/*/obj/local -mx9 -r
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.PAT_GITHUB_TOKEN }}
        tag_name: workflow_${{github.run_number}}
        name: Release ${{github.run_number}}
        files: |
           app/build/outputs/apk/debug/app-debug.apk
           library.zip
